stages:
  - apibuild
  - androidbuild
  
api-build:
    stage: apibuild
    tags:
      - Backend
    script:
      - cd Backend/WebAppliaion-mc_02
      - sudo docker build --network="host" -t mybuild -f DockerfileBuild .
      
android-build:
    image: javiersantos/android-ci:latest
    stage: androidbuild
    before_script:
        - export GRADLE_USER_HOME='pwd'/.gradle
        - chmod +x ./Frontend/ExercyzeFrontend/gradlew
    tags:
        - FRONTEND
    script:
        - cd Frontend/FinalApp
        - ./gradlew assemble
    artifacts:
        paths:
            - Frontend/ExercyzeFrontend/app/build/outputs/