stages:
  - apibuild
  - androidbuild
  
api-build:
    stage: apibuild
    tags:
      - Backend
    script:
      - cd Backend/WebAppliaion-mc_02
      - sudo docker build --network="host" -t mybuild -f DockerfileBuild .
      
android-build:
    stage: androidbuild
    tags:
        - FRONTEND
    script:
        - cd Frontend/FinalApp/
        - ./gradlew assemble